import { starArray } from "../../components/stars/stars.type";

export const starsMyProjectsMobile: starArray = [
  // left part | mobile
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "47px",
    transform: "translate(calc(-50% - 109px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "49px",
    transform: "translate(calc(-50% - 36px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "56px",
    transform: "translate(calc(-50% - 49px))",
    animationType: "short",
  },
  {
    type: "small",
    color: "var(--gainsboro)",
    top: "68px",
    transform: "translate(calc(-50% - 151px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "119px",
    transform: "translate(calc(-50% - 152px))",
    animationType: "short",
  },
  {
    type: "small",
    color: "var(--gainsboro)",
    top: "168px",
    transform: "translate(calc(-50% - 158px))",
    animationType: "short",
  },
  // right part | mobile
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "46px",
    transform: "translate(calc(-50% + 143px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro-opacity-05)",
    top: "69px",
    transform: "translate(calc(-50% + 79px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "79px",
    transform: "translate(calc(-50% + 61px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "169px",
    transform: "translate(calc(-50% + 130px))",
    animationType: "short",
  },
];
export const starsMyProjectsTablet: starArray = [
  // left part | Tablet
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "74px",
    transform: "translate(calc(-50% - 257px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "98px",
    transform: "translate(calc(-50% - 226px))",
    animationType: "short",
  },
  // right part | Tablet
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "25px",
    transform: "translate(calc(-50% + 204px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "84px",
    transform: "translate(calc(-50% + 333px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "108px",
    transform: "translate(calc(-50% + 264px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "149px",
    transform: "translate(calc(-50% + 206px))",
    animationType: "short",
  },
];
export const starsMyProjectsDesktop: starArray = [
  // left part | Desktop
  {
    type: "small",
    color: "var(--gainsboro)",
    top: "40px",
    transform: "translate(calc(-50% - 379px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "40px",
    transform: "translate(calc(-50% - 231px))",
    animationType: "short",
  },
  {
    type: "small",
    color: "var(--gainsboro)",
    top: "42px",
    transform: "translate(calc(-50% - 46px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "47px",
    transform: "translate(calc(-50% - 456px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "70px",
    transform: "translate(calc(-50% - 424px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "70px",
    transform: "translate(calc(-50% - 424px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "85px",
    transform: "translate(calc(-50% - 554px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "90px",
    transform: "translate(calc(-50% - 67px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "105px",
    transform: "translate(calc(-50% - 268px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "117px",
    transform: "translate(calc(-50% - 422px))",
    animationType: "short",
  },
  {
    type: "small",
    color: "var(--gainsboro)",
    top: "166px",
    transform: "translate(calc(-50% - 469px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "146px",
    transform: "translate(calc(-50% - 339px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "171px",
    transform: "translate(calc(-50% - 559px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "178px",
    transform: "translate(calc(-50% - 233px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "279px",
    left: "32px",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "360px",
    left: "41px",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "833px",
    left: "23px",
    animationType: "short",
  },
  // right part | Desktop
];
export const starsMyProjectsMonitor: starArray = [
  // left part | Monitor
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "58px",
    transform: "translate(calc(-50% - 846px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro-opacity-02)",
    top: "62px",
    transform: "translate(calc(-50% - 575px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "88px",
    transform: "translate(calc(-50% - 666px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "89px",
    transform: "translate(calc(-50% - 67px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "130px",
    transform: "translate(calc(-50% - 334px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "177px",
    transform: "translate(calc(-50% - 559px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "224px",
    transform: "translate(calc(-50% - 851px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "231px",
    transform: "translate(calc(-50% - 516px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "251px",
    transform: "translate(calc(-50% - 447px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "288px",
    transform: "translate(calc(-50% - 725px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "321px",
    transform: "translate(calc(-50% - 596px))",
    animationType: "short",
  },
  // right part | Monitor
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "45px",
    transform: "translate(calc(-50% + 46px))",
    animationType: "short",
  },
  {
    type: "big",
    color: "var(--gainsboro)",
    top: "112px",
    transform: "translate(calc(-50% + 29px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "378px",
    transform: "translate(calc(-50% + 83px))",
    animationType: "short",
  },
  {
    type: "large",
    color: "var(--gainsboro)",
    top: "492px",
    transform: "translate(calc(-50% + 84px))",
    animationType: "short",
  },
  {
    type: "medium",
    color: "var(--gainsboro)",
    top: "569px",
    transform: "translate(calc(-50% + 44px))",
    animationType: "short",
  },
];
